config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "/tasks", to: "tasks#index" # read all
  # get "/tasks/new", to: "tasks#new" # new GET

  # get "/tasks/:id", to: "tasks#show", as: :task # read one

  # post "/tasks", to: "tasks#create" # create POST
  # get "/tasks/:id/edit", to: "tasks#edit" # edit GET
  # patch "/tasks/:id", to: "tasks#update" # mise a jour PATCH
  # delete "/tasks/:id", to: "tasks#destroy" # delete

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    # no need for app/views/tasks/create.html.erb
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="formulaire">
  <%= form_for(@task) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
    <%= f.submit %>

  <% end %>
  </div>

app/views/tasks/index.html.erb
<!-- app/views/tasks/index.html.erb -->
<div class="container">

<h1>Mes taches</h1>
<div class="ul">
<ul>
  <% @tasks.each do |task| %>
    <li>
      <div>
        <% if task.completed %>
          <i class="fas fa-check-square"></i>
        <% else  %>
          <i class="far fa-square"></i>
        <% end %>

        <%= link_to task.title, task_path(task.id)  %>

        <%= link_to task_path(task),
            method: :delete,
            data: { confirm: "Voulez-vous supprimer cette tache ?" } do %>
            <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>
</div>

<div class="add">
  <i class="fas fa-plus"></i>
  <%= link_to " Ajouter une nouvelle tache", new_task_path %>

</div>
</div>

app/views/tasks/new.html.erb
<div class="formulaire">
  <%= form_for(@task) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.submit %>

  <% end %>
  </div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="edit">
    <h1><%= @task.title %></h1>
    <a href="/tasks/<%= @task.id %>/edit" class="btn btn-primary">Editer tache</a>
  </div>
  <h3 class="content"><%= @task.details %></h3>
  <% if @task.completed %>
    <p>
      <i class="fas fa-check-square">  Cette tache est faite, bien joué</i>
    </p>
  <% else  %>
    <p>
      <i class="fas fa-square">  Cette tache est à faire feignasse</i>
    </p>
  <% end %>

  <div>
    <i class="fas fa-undo"></i>
    <%= link_to " Retour à la liste des taches", tasks_path %>
  </div>
</div>